### ISSUE TITLE
Template renaming should not be exclusive to components

### ISSUE THREAD

**Issue by lukasjarosch** [lukasjarosch/skipper#32]
Currently, the templater only allows renames for component rendering.
But it would be nice to be able to expose that functionality to the other template rendering methods `Execute` and `ExecuteAll`.

This would introduce just a small change and generalise the use of Skipper even more.

**Comment by alxndr13** [comment]
i'll work on this one, maybe i'll come up with something in the next hour or so

**Comment by alxndr13** [comment]
i'm not able to get the `make` example tests running, maybe i need some more infos the next few days :)

**Comment by lukasjarosch** [comment]
The `secret` example is currently the one whith which I am working and should be running. I'm not sure about the other examples.

**Comment by alxndr13** [comment]
Seems like the others do not work anymore.. i'll see what i can do :)

**Comment by alxndr13** [comment]
pushed a first draft into https://github.com/lukasjarosch/skipper/pull/34

**Comment by lukasjarosch** [comment]
You rock 🚀, thanks for contributing in the first place.
I've added a few comments to the PR, I like it 😄. 

I've added a feature request https://github.com/lukasjarosch/skipper/issues/36 to work on the examples and make them more meaningful in the future.
